---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: files/(issue|motd)
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: pretty-format-json
        args:
          - --autofix
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint
        # The LICENSE.md must match the license text exactly for
        # GitHub's autorecognition fu to work, so we should leave it
        # alone.
        exclude: LICENSE.md
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.1
    hooks:
      - id: yamllint
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.13.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
  - repo: https://github.com/ambv/black
    rev: 21.4b1
    hooks:
      - id: black
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v5.0.7
    hooks:
      - id: ansible-lint
      # files: molecule/default/playbook.yml
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
      - id: docker-compose-check
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
