language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install -e .[dev]
  - pip install flake8 pytest-cov coveralls

script:
  - pytest --cov=cyhy/mailer
  - flake8 .

after_success:
  - coveralls
