---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

env:
  global:
    - IMAGE_NAME=dhsncats/cyhy-mailer
    - DOCKER_USER=jsf9k
    - secure: "g3qn0JOrncGsKm22muuj1vpLnmV2P3vaIDU6f3XOb2zPhpFO6P9Ptq/\
      hhV6TCj6uil5A41qOuw3/m/DFxSQQS08U+WhXhDodCH0xP3OxrhtX4c9MXo5cB4Y\
      9Fd8UehqGs4E5cRbVOQglQ5t98xP+iVa5dBpbEyqw2V06EO6SCYNlBrvjn2dNPUb\
      SfUFkA211AOq4b3meRW+OwOJ7I69mlb90aKCaYODuOYF+LjSftLqkEgHYIxVscBv\
      aQxfeXI0/mfo9D3wKqTU1JI2xFiUub5fGRtxhUVOKMdgFz9aizmxdbjl5Xga8/3+\
      6Iw/5bdSkLkf6/z7/V9tuEpNVywPh5Df30C0NT8Wn27+odQx5OKjnnN0d4SfIPbh\
      Pl5hPKn9qcVvdB8aRnbAedLcbWOIP6dq1Dx/Z3/E4MWDoO6JMM8iJ5m9jRx0T7BZ\
      s6GiKMUf69d49a00PdgvmMdN/6FjKXZYw97359iiF2NQi0WabtC6HTH/SJR68Sc4\
      5pFDw1WqIIYCw7O93mc94AdG69fu9sAh50tLat0NYr16Q8+b+CQUmtTvsBogQZGO\
      TJgfqH32AFXcF2Rb0h/f+QDHrWZPhFqW2vzeMPRAL8JJ+a9mD+1mrCjMCNuC23Wk\
      OI7MWZ4gyMhWMncFUvIwqUk4JFhyOLjKGEcBni+zCred2S3SJip4="

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt

script:
  - pre-commit run --all-files
  - pytest --cov=cyhy/mailer
  - travis_scripts/build_docker_image.sh

after_success:
  - coveralls

deploy:
  - provider: script
    script: bash travis_scripts/deploy_to_docker_hub.sh
    on:
      tags: true
      python: '3.7'
