version: '3.2'

secrets:
  database_creds:
    file: ./secrets/database_creds.yml
  aws_config:
    file: ./secrets/aws_config

services:
  mailer:
    image: 'dhsncats/cyhy-mailer:1.1.0'
    secrets:
      - source: database_creds
        target: database_creds.yml
      - source: aws_config
        target: aws_config
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=default
    volumes:
      - type: bind
        source: /var/cyhy/weekly_reporting/report_archive/latest
        target: /cyhy_reports
      - type: bind
        source: /var/cyhy/weekly_reporting/scorecards/latest
        target: /cybex_scorecard
    command: ["report", "--cyhy-report-dir=/cyhy_reports/", "--cybex-scorecard-dir=/cybex_scorecard/", "--db-creds-file=/run/secrets/database_creds.yml", "--summary-to=ncats@hq.dhs.gov,jeremy.frasier@trio.dhs.gov,ncats-dev@beta.dhs.gov"]
